# Generated by Django 5.2.7 on 2025-10-03 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Layanan')),
                ('description', models.TextField(blank=True, help_text='Penjelasan singkat layanan', null=True, verbose_name='Deskripsi')),
                ('users', models.CharField(help_text='Target pengguna layanan (Dosen, Mahasiswa, Staf, dsb.)', max_length=255, verbose_name='Pengguna')),
                ('request_method', models.CharField(help_text='Jalur untuk request (Helpdesk IT, Portal Helpdesk, Website PMB, dll.)', max_length=255, verbose_name='Cara Request')),
                ('sla', models.CharField(help_text='Respon & waktu penyelesaian (Respon 30 menit, selesai 1 jam, dll.)', max_length=255, verbose_name='SLA')),
                ('pic', models.CharField(help_text='Tim penanggung jawab (Tim Infrastruktur, Tim Aplikasi, Tim Support, dll.)', max_length=100, verbose_name='PIC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Layanan',
                'verbose_name_plural': 'Layanan',
                'ordering': ['category', 'name'],
            },
        ),
    ]
